config/routes.rb
AskFm::Application.routes.draw do
  root "static_pages#home"

  get "/timeline", to: "static_pages#timeline"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/latest", to: "static_pages#latest"

  get "/signup", to: "users#new"
  resources :users, only: [:index, :create, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
    resources :questions, only: [:create] do
      resources :notifications, only: [:create]
    end
    resources :answers, only: [:show] do
      resources :notifications, only: [:create]
    end
  end

  resources :notifications, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :questions, only: [:index] do
    resources :answers, only: [:create]
    collection do
    end
  end
  get "/need-to-answer", to: "questions#need_to_answer", as: "need_to_answer"
  get "/questions/:id/reply", to: "questions#reply", as: "reply"

  get "/login", "/signin", to: "sessions#new"
  resources :sessions, only: [:create, :destroy]
  delete "/logout", "/signout", to: "sessions#destroy"
  

  

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  content     :string(255)
#  user_id     :integer
#  receiver_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#  replied     :boolean          default(FALSE)
#

class Question < ActiveRecord::Base
  validates :content, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true
  validates :receiver_id, presence: true
  belongs_to :user
  #belongs_to :sender, class_name: "User", foreign_key: "user_id"
  #belongs_to :receiver, class_name: "User"
  has_one :answer, dependent: :destroy
  has_one :notification, as: :notifiable

  after_create :send_notification

  private
    def send_notification
      self.create_notification(user_id: self.receiver_id)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :signed_in_user?, only: [:index, :need_to_answer, :reply, :create]
  def index
    # 这个 action 是列出用户提出的问题
    @questions = current_user.questions.page(params[:page]).per(20)
  end

  def need_to_answer
    # 这个 action 是列出用户收到的问题
    @receive_questions = current_user.receive_questions.where(replied: false)
  end

  def create
    @user = current_user
    @question = @user.questions.create(content: params[:question][:content],
                                       receiver_id: params[:user_id]
                                      )
    redirect_to User.find(params[:user_id])
  end

  def reply
    @question = Question.find(params[:id])
    if @question.replied?
      flash[:notice] = "那个问题已经回答过咯"
      redirect_to root_path
    end
    @answer = @question.build_answer
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def owner_of(item)
    User.find(item.user_id)
  end

  def receiver_of(item)
    User.find(item.receiver_id)
  end
end

app/views/questions/_question.html.haml
.question
  .content= question.content
  = link_to owner_of(question).name, user_path(owner_of(question)), class: "name"
  .date= time_ago_in_words question.created_at
  = link_to "回答", reply_path(question), class: "reply"

app/views/questions/index.html.haml
%h1 问题(好啦，我知道这个页面没什么意义，只是不把它做出来我就难受这样总可以吧)

.questions
  - @questions.each do |question|
    .question
      To: 
      = link_to receiver_of(question).name, user_path(receiver_of(question)), class: "name"
      .date= time_ago_in_words question.created_at
      .content= question.content

= paginate @questions

app/views/questions/need_to_answer.html.haml
%h1 Need To Answer

.need_to_answer
  - @receive_questions.each do |question|
    //.question
    //  .content= question.content
    //  = link_to owner_of(question).name, user_path(owner_of(question)), class: "name"
    //  .date= time_ago_in_words question.created_at
    //  = link_to "回答", reply_path(question), class: "reply"
    = render partial: 'question', locals: { question: question }

app/views/questions/reply.html.haml
%h1 问题

.reply
  = @question.content
  
  = form_for [@question, @answer] do |f|
    = f.text_area :content
    .post
      .counter= 200
      = f.submit "回答", class: "button disabled", disabled: "disabled"