config/routes.rb
AskFm::Application.routes.draw do
  root "static_pages#home"

  get "/timeline", to: "static_pages#timeline"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/latest", to: "static_pages#latest"

  get "/signup", to: "users#new"
  resources :users, only: [:index, :create, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
    resources :questions, only: [:create] do
      resources :notifications, only: [:create]
    end
    resources :answers, only: [:show] do
      resources :notifications, only: [:create]
    end
  end

  resources :notifications, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :questions, only: [:index] do
    resources :answers, only: [:create]
    collection do
    end
  end
  get "/need-to-answer", to: "questions#need_to_answer", as: "need_to_answer"
  get "/questions/:id/reply", to: "questions#reply", as: "reply"

  get "/login", "/signin", to: "sessions#new"
  resources :sessions, only: [:create, :destroy]
  delete "/logout", "/signout", to: "sessions#destroy"
  

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :signed_in_user?, only: [:timeline]
  def home
    if signed_in?
      feeds
      render :timeline
    end
    @signuped_users = User.order(created_at: :desc).limit(10)
  end

  def help
  end

  def about
  end

  def popular
  end

  def latest
    @answers = Answer.order(created_at: :desc).page(params[:page]).per(20)
  end

  def timeline
    feeds
  end

  private
    def feeds
      @feed_items = current_user.feed.page(params[:page]).per(20)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
%h1 About

.about
  %h3 大概就是照着 #{link_to "ask.fm", "http://ask,fm"} 做的。
  %h3 这里只是个 demo 而已，代码在 #{link_to "GitHub", "https://github.com/messiahxu/AskFm"}。
  
  %h4 TODO:
  %ul
    %li 重写 following followers 页面的关注、取消关注功能。
    %li 收到问题，收到回答的通知功能。

app/views/static_pages/help.html.haml
%h1 帮助

.help
  %h3 好吧，我承认，这个页面也是没什么用处的……
  %h3 没错，具体的什么去看 #{link_to "关于", about_path} 就好了。

app/views/static_pages/home.html.haml
.signup_screen
  .signup_box
    %h1 问与答
    %p= link_to "注册吧", signup_path, class: "button button-large signup"
  
  不想注册？先看看别人怎么玩儿也好啦。
  = link_to "最近回答", latest_path

.signuped_users 
  %strong 已注册用户
  .users-list
    - @signuped_users.each do |user|
      = link_to gravatar_for(user), user

app/views/static_pages/latest.html.haml
%h1 Latest

.timeline
  .answers-list
    .answers
      - @answers.each do |answer|
        .answer
          = gravatar_for(owner_of(answer))
          .box
            .content
              .question_content= answer.question.content
              = link_to owner_of(answer.question).name, user_path(owner_of(answer.question))
              .answer_content= answer.content
              .date= time_ago_in_words answer.created_at
              = link_to owner_of(answer).name, user_path(owner_of(answer))
  

app/views/static_pages/timeline.html.haml
%h1 时间线

.timeline
  .answers-list
    .answers
      - @feed_items.each do |answer|
        = render partial: 'answers/answer', locals: { answer: answer }

= paginate @feed_items