config/routes.rb
AskFm::Application.routes.draw do
  root "static_pages#home"

  get "/timeline", to: "static_pages#timeline"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/latest", to: "static_pages#latest"

  get "/signup", to: "users#new"
  resources :users, only: [:index, :create, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
    resources :questions, only: [:create] do
      resources :notifications, only: [:create]
    end
    resources :answers, only: [:show] do
      resources :notifications, only: [:create]
    end
  end

  resources :notifications, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :questions, only: [:index] do
    resources :answers, only: [:create]
    collection do
    end
  end
  get "/need-to-answer", to: "questions#need_to_answer", as: "need_to_answer"
  get "/questions/:id/reply", to: "questions#reply", as: "reply"

  get "/login", "/signin", to: "sessions#new"
  resources :sessions, only: [:create, :destroy]
  delete "/logout", "/signout", to: "sessions#destroy"
  

  

end

app/views/layouts/_footer.html.haml
%footer
  %nav
    = link_to "ask.fm", root_path, class: "logo"
    %ul.pull_right
      %li= link_to "About", "#"
      %li= mail_to "messiahxu@gmail.com", "Contact"
      %li= link_to "News", "https://twitter.com/messiahxu", target: "_blank"

app/views/layouts/_header.html.haml
%header
  %nav
    = link_to "ask.fm", root_path, class: "logo"
    %ul.pull_right
      - if signed_in?
        %li= link_to @unread_count, notifications_path, class: "notification #{'unread' if @unread_count != 0}"
      %li= link_to "首页", root_path
      %li= link_to "帮助", help_path
      %li= link_to "关于", about_path
      - if signed_in?
        %li= link_to "Users", users_path
        %li.toggle_drop_down
          %a{href: "#", title: current_user.name}= current_user.name.size>3 ? current_user.name[0...3]+'...' : current_user.name
          %ul.drop_down
            %li= link_to "个人页面", user_path(current_user)
            %Li= link_to "修改资料", edit_user_path(current_user)
            %li= link_to "问题", questions_path
            %li= link_to "尚未回答", need_to_answer_path
            %li= link_to "注销登录", signout_path, method: :delete
      - else 
        %li= link_to "登录", signin_path 
        %li= link_to "注册", signup_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AskFm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  <%= debug(params) if Rails.env.development? %>

</body>
</html>